/**
 * Professional Export Utilities for CSV and PDF generation
 * Includes letterhead, branding, and professional formatting
 */

import { logger } from './monitoring';

export interface ExportData {
  headers: string[];
  rows: (string | number)[][];
}

export interface ReportConfig {
  title: string;
  subtitle?: string;
  generatedBy?: string;
  dateRange?: { start: string; end: string };
  filters?: Record<string, string>;
  language?: 'en' | 'fr';
}

// Company branding info
const COMPANY_INFO = {
  name: 'RiadPrix',
  tagline: 'Revenue Intelligence for Moroccan Hospitality',
  website: 'www.riadprix.com',
  email: 'reports@riadprix.com',
};

// Format date for reports
function formatReportDate(date: Date, language: 'en' | 'fr' = 'en'): string {
  const options: Intl.DateTimeFormatOptions = {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  };
  return date.toLocaleDateString(language === 'fr' ? 'fr-FR' : 'en-US', options);
}

// Generate unique report ID
function generateReportId(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `RPX-${timestamp}-${random}`;
}

// Professional CSV Export with metadata header
export function exportToCSV(
  data: ExportData,
  filename: string = 'export.csv',
  config?: ReportConfig
) {
  try {
    const reportId = generateReportId();
    const generatedAt = formatReportDate(new Date(), config?.language);
    const lang = config?.language || 'en';
    
    // Build metadata header section
    const metadataLines: string[] = [];
    metadataLines.push(`"${COMPANY_INFO.name} - ${lang === 'fr' ? 'Rapport Exporté' : 'Exported Report'}"`);
    metadataLines.push(`"${config?.title || (lang === 'fr' ? 'Rapport de Données' : 'Data Report')}"`);
    if (config?.subtitle) {
      metadataLines.push(`"${config.subtitle}"`);
    }
    metadataLines.push('""'); // Empty line
    metadataLines.push(`"${lang === 'fr' ? 'ID du Rapport' : 'Report ID'}","${reportId}"`);
    metadataLines.push(`"${lang === 'fr' ? 'Généré le' : 'Generated On'}","${generatedAt}"`);
    if (config?.generatedBy) {
      metadataLines.push(`"${lang === 'fr' ? 'Généré par' : 'Generated By'}","${config.generatedBy}"`);
    }
    if (config?.dateRange) {
      metadataLines.push(`"${lang === 'fr' ? 'Période' : 'Date Range'}","${config.dateRange.start} - ${config.dateRange.end}"`);
    }
    if (config?.filters) {
      Object.entries(config.filters).forEach(([key, value]) => {
        metadataLines.push(`"${key}","${value}"`);
      });
    }
    metadataLines.push('""'); // Empty line separator
    metadataLines.push(`"=== ${lang === 'fr' ? 'DÉBUT DES DONNÉES' : 'DATA SECTION START'} ==="`);
    metadataLines.push('""');

    // Build data section
    const dataLines: string[] = [];
    dataLines.push(data.headers.map(h => `"${String(h).replace(/"/g, '""')}"`).join(','));
    data.rows.forEach(row => {
      dataLines.push(row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(','));
    });

    // Build footer section
    const footerLines: string[] = [];
    footerLines.push('""');
    footerLines.push(`"=== ${lang === 'fr' ? 'FIN DES DONNÉES' : 'DATA SECTION END'} ==="`);
    footerLines.push('""');
    footerLines.push(`"${lang === 'fr' ? 'Total des enregistrements' : 'Total Records'}","${data.rows.length}"`);
    footerLines.push('""');
    footerLines.push(`"${lang === 'fr' ? 'Avertissement' : 'Disclaimer'}","${lang === 'fr' ? 'Ces données sont fournies à titre informatif uniquement. RiadPrix ne garantit pas l\'exactitude des estimations de marché.' : 'This data is provided for informational purposes only. RiadPrix does not guarantee the accuracy of market estimates.'}"`);
    footerLines.push(`"${lang === 'fr' ? 'Contact' : 'Contact'}","${COMPANY_INFO.email}"`);
    footerLines.push(`"${lang === 'fr' ? 'Site Web' : 'Website'}","${COMPANY_INFO.website}"`);
    footerLines.push('""');
    footerLines.push(`"© ${new Date().getFullYear()} ${COMPANY_INFO.name}. ${lang === 'fr' ? 'Tous droits réservés.' : 'All rights reserved.'}"`);

    // Combine all sections
    const csvContent = [...metadataLines, ...dataLines, ...footerLines].join('\n');

    // Add BOM for Excel UTF-8 compatibility
    const BOM = '\uFEFF';
    const blob = new Blob([BOM + csvContent], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);

    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
    logger.info('CSV export completed', { filename, reportId });
    return reportId;
  } catch (error) {
    logger.error('CSV export failed', error as Error);
    throw error;
  }
}

// Professional PDF Export with letterhead and footer
export async function exportToPDF(data: {
  title: string;
  content: string | ExportData;
  config?: ReportConfig;
  filename?: string;
}) {
  try {
    const reportId = generateReportId();
    const generatedAt = formatReportDate(new Date(), data.config?.language);
    const lang = data.config?.language || 'en';

    // Build HTML content for PDF
    let tableHTML = '';
    if (typeof data.content !== 'string' && 'headers' in data.content && 'rows' in data.content) {
      const exportData = data.content as ExportData;
      tableHTML = `
        <table>
          <thead>
            <tr>
              ${exportData.headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${exportData.rows.map(row => `
              <tr>
                ${row.map(cell => `<td>${cell}</td>`).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>
        <p class="record-count">${lang === 'fr' ? 'Total des enregistrements' : 'Total Records'}: ${exportData.rows.length}</p>
      `;
    } else {
      tableHTML = `<div class="content-section">${data.content}</div>`;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      throw new Error('Could not open print window. Please allow popups for this site.');
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html lang="${lang}">
        <head>
          <meta charset="UTF-8">
          <title>${data.title} - ${COMPANY_INFO.name}</title>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
            
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            
            @page {
              size: A4;
              margin: 20mm 15mm 30mm 15mm;
            }
            
            body {
              font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
              font-size: 11px;
              line-height: 1.5;
              color: #1a1a2e;
              background: white;
              padding: 0;
            }
            
            /* Header / Letterhead */
            .letterhead {
              display: flex;
              justify-content: space-between;
              align-items: flex-start;
              padding-bottom: 20px;
              border-bottom: 3px solid #d4a574;
              margin-bottom: 25px;
            }
            
            .logo-section {
              display: flex;
              align-items: center;
              gap: 12px;
            }
            
            .logo {
              width: 50px;
              height: 50px;
              background: linear-gradient(135deg, #d4a574, #8b5a2b);
              border-radius: 10px;
              display: flex;
              align-items: center;
              justify-content: center;
              color: white;
              font-weight: 700;
              font-size: 20px;
            }
            
            .company-name {
              font-size: 24px;
              font-weight: 700;
              color: #1a1a2e;
              letter-spacing: -0.5px;
            }
            
            .company-tagline {
              font-size: 10px;
              color: #666;
              margin-top: 2px;
            }
            
            .report-meta {
              text-align: right;
              font-size: 10px;
              color: #666;
            }
            
            .report-id {
              font-family: monospace;
              font-size: 11px;
              color: #d4a574;
              font-weight: 600;
            }
            
            /* Report Title Section */
            .report-header {
              text-align: center;
              margin-bottom: 30px;
              padding: 20px;
              background: linear-gradient(135deg, #f8f4f0, #fff);
              border-radius: 8px;
              border-left: 4px solid #d4a574;
            }
            
            .report-title {
              font-size: 22px;
              font-weight: 700;
              color: #1a1a2e;
              margin-bottom: 5px;
            }
            
            .report-subtitle {
              font-size: 13px;
              color: #666;
            }
            
            .report-filters {
              margin-top: 15px;
              display: flex;
              justify-content: center;
              gap: 20px;
              flex-wrap: wrap;
            }
            
            .filter-item {
              font-size: 10px;
              background: white;
              padding: 5px 12px;
              border-radius: 15px;
              border: 1px solid #e0e0e0;
            }
            
            .filter-label {
              color: #888;
            }
            
            .filter-value {
              font-weight: 600;
              color: #1a1a2e;
            }
            
            /* Data Table */
            table {
              width: 100%;
              border-collapse: collapse;
              margin: 20px 0;
              font-size: 10px;
            }
            
            th {
              background: #1a1a2e;
              color: white;
              padding: 12px 10px;
              text-align: left;
              font-weight: 600;
              text-transform: uppercase;
              letter-spacing: 0.5px;
              font-size: 9px;
            }
            
            th:first-child {
              border-radius: 6px 0 0 0;
            }
            
            th:last-child {
              border-radius: 0 6px 0 0;
            }
            
            td {
              padding: 10px;
              border-bottom: 1px solid #e8e8e8;
              color: #333;
            }
            
            tr:nth-child(even) {
              background: #fafafa;
            }
            
            tr:hover {
              background: #f5f0eb;
            }
            
            tr:last-child td:first-child {
              border-radius: 0 0 0 6px;
            }
            
            tr:last-child td:last-child {
              border-radius: 0 0 6px 0;
            }
            
            .record-count {
              text-align: right;
              font-size: 11px;
              color: #666;
              margin-top: 10px;
              font-weight: 500;
            }
            
            /* Content Section */
            .content-section {
              padding: 20px;
              background: #fafafa;
              border-radius: 8px;
              margin: 20px 0;
            }
            
            /* Footer */
            .footer {
              position: fixed;
              bottom: 0;
              left: 0;
              right: 0;
              background: #f8f8f8;
              padding: 15px 30px;
              border-top: 2px solid #d4a574;
              font-size: 9px;
              display: flex;
              justify-content: space-between;
              align-items: center;
            }
            
            .footer-left {
              color: #666;
            }
            
            .footer-center {
              text-align: center;
              color: #888;
            }
            
            .footer-right {
              text-align: right;
              color: #666;
            }
            
            .disclaimer {
              background: #fff9f0;
              border: 1px solid #f0e0d0;
              border-radius: 6px;
              padding: 12px 15px;
              margin: 25px 0;
              font-size: 9px;
              color: #8b5a2b;
            }
            
            .disclaimer-title {
              font-weight: 600;
              margin-bottom: 5px;
              color: #6b4423;
            }
            
            /* Print specific */
            @media print {
              body {
                print-color-adjust: exact;
                -webkit-print-color-adjust: exact;
              }
              
              .footer {
                position: fixed;
                bottom: 0;
              }
              
              .no-print {
                display: none;
              }
            }
          </style>
        </head>
        <body>
          <!-- Letterhead -->
          <div class="letterhead">
            <div class="logo-section">
              <div class="logo">RP</div>
              <div>
                <div class="company-name">${COMPANY_INFO.name}</div>
                <div class="company-tagline">${COMPANY_INFO.tagline}</div>
              </div>
            </div>
            <div class="report-meta">
              <div class="report-id">${reportId}</div>
              <div style="margin-top: 5px;">${generatedAt}</div>
              ${data.config?.generatedBy ? `<div>${lang === 'fr' ? 'Généré par' : 'Generated by'}: ${data.config.generatedBy}</div>` : ''}
            </div>
          </div>
          
          <!-- Report Header -->
          <div class="report-header">
            <h1 class="report-title">${data.title}</h1>
            ${data.config?.subtitle ? `<p class="report-subtitle">${data.config.subtitle}</p>` : ''}
            ${data.config?.dateRange || data.config?.filters ? `
              <div class="report-filters">
                ${data.config?.dateRange ? `
                  <span class="filter-item">
                    <span class="filter-label">${lang === 'fr' ? 'Période' : 'Period'}:</span>
                    <span class="filter-value">${data.config.dateRange.start} → ${data.config.dateRange.end}</span>
                  </span>
                ` : ''}
                ${data.config?.filters ? Object.entries(data.config.filters).map(([key, value]) => `
                  <span class="filter-item">
                    <span class="filter-label">${key}:</span>
                    <span class="filter-value">${value}</span>
                  </span>
                `).join('') : ''}
              </div>
            ` : ''}
          </div>
          
          <!-- Data Content -->
          ${tableHTML}
          
          <!-- Disclaimer -->
          <div class="disclaimer">
            <div class="disclaimer-title">${lang === 'fr' ? 'Avertissement' : 'Disclaimer'}</div>
            ${lang === 'fr' 
              ? 'Ces données sont fournies à titre informatif uniquement. Les estimations de marché sont basées sur des données agrégées et peuvent ne pas refléter les conditions exactes du marché. RiadPrix ne garantit pas l\'exactitude des projections de revenus ou des recommandations de prix. Consultez toujours un conseiller professionnel avant de prendre des décisions commerciales importantes.'
              : 'This data is provided for informational purposes only. Market estimates are based on aggregated data and may not reflect exact market conditions. RiadPrix does not guarantee the accuracy of revenue projections or pricing recommendations. Always consult with a professional advisor before making significant business decisions.'}
          </div>
          
          <!-- Footer -->
          <div class="footer">
            <div class="footer-left">
              <strong>${COMPANY_INFO.name}</strong><br>
              ${COMPANY_INFO.email} | ${COMPANY_INFO.website}
            </div>
            <div class="footer-center">
              ${lang === 'fr' ? 'Document confidentiel' : 'Confidential Document'}<br>
              ${lang === 'fr' ? 'Page 1 sur 1' : 'Page 1 of 1'}
            </div>
            <div class="footer-right">
              © ${new Date().getFullYear()} ${COMPANY_INFO.name}<br>
              ${lang === 'fr' ? 'Tous droits réservés' : 'All rights reserved'}
            </div>
          </div>
          
          <script>
            window.onload = function() {
              setTimeout(function() {
                window.print();
              }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();

    logger.info('PDF export initiated', { title: data.title, reportId });
    return reportId;
  } catch (error) {
    logger.error('PDF export failed', error as Error);
    throw error;
  }
}

// Helper to format benchmark data for export
export function formatBenchmarkDataForExport(benchmarks: Array<{
  property_type: string;
  min_price: number | null;
  median_price: number | null;
  max_price: number | null;
  period_start: string;
  period_end: string;
}>): ExportData {
  return {
    headers: ['Property Type', 'Min Price (MAD)', 'Median Price (MAD)', 'Max Price (MAD)', 'Period Start', 'Period End'],
    rows: benchmarks.map(b => [
      b.property_type,
      b.min_price || 0,
      b.median_price || 0,
      b.max_price || 0,
      b.period_start,
      b.period_end,
    ]),
  };
}

// Format market data for export
export function formatMarketDataForExport(
  marketData: Array<{
    date: string;
    avg_price: number | null;
    occupancy_rate: number | null;
    property_type: string;
  }>,
  language: 'en' | 'fr' = 'en'
): ExportData {
  const headers = language === 'fr'
    ? ['Date', 'Prix Moyen (MAD)', 'Taux d\'Occupation (%)', 'Type de Propriété']
    : ['Date', 'Average Price (MAD)', 'Occupancy Rate (%)', 'Property Type'];

  return {
    headers,
    rows: marketData.map(d => [
      d.date,
      d.avg_price || 0,
      d.occupancy_rate ? `${d.occupancy_rate}%` : 'N/A',
      d.property_type,
    ]),
  };
}

// Format property data for export
export function formatPropertyDataForExport(
  properties: Array<{
    name: string;
    property_type: string;
    current_price: number | null;
    bedrooms: number | null;
    bathrooms: number | null;
    max_guests: number | null;
  }>,
  language: 'en' | 'fr' = 'en'
): ExportData {
  const headers = language === 'fr'
    ? ['Nom', 'Type', 'Prix Actuel (MAD)', 'Chambres', 'Salles de Bain', 'Capacité Max']
    : ['Name', 'Type', 'Current Price (MAD)', 'Bedrooms', 'Bathrooms', 'Max Guests'];

  return {
    headers,
    rows: properties.map(p => [
      p.name,
      p.property_type,
      p.current_price || 'N/A',
      p.bedrooms || 'N/A',
      p.bathrooms || 'N/A',
      p.max_guests || 'N/A',
    ]),
  };
}

// Format recommendations for export
export function formatRecommendationsForExport(
  recommendations: Array<{
    property_name: string;
    current_price: number;
    recommended_price: number;
    confidence_score: number | null;
    valid_from: string;
    valid_to: string;
    reasoning: string | null;
  }>,
  language: 'en' | 'fr' = 'en'
): ExportData {
  const headers = language === 'fr'
    ? ['Propriété', 'Prix Actuel (MAD)', 'Prix Recommandé (MAD)', 'Variation (%)', 'Confiance', 'Valide Du', 'Valide Au', 'Raisonnement']
    : ['Property', 'Current Price (MAD)', 'Recommended Price (MAD)', 'Change (%)', 'Confidence', 'Valid From', 'Valid To', 'Reasoning'];

  return {
    headers,
    rows: recommendations.map(r => {
      const change = ((r.recommended_price - r.current_price) / r.current_price * 100).toFixed(1);
      return [
        r.property_name,
        r.current_price,
        r.recommended_price,
        `${change}%`,
        r.confidence_score ? `${(r.confidence_score * 100).toFixed(0)}%` : 'N/A',
        r.valid_from,
        r.valid_to,
        r.reasoning || 'N/A',
      ];
    }),
  };
}
